
languages:
  supported:
    - en
    - fr
    - it
  default_lang: en
  include_default_lang: true
  include_default_lang_file_extension: true
  translations_fallback: true
  http_accept_language: true
home:
  alias: /home
pages:
  theme: grama
  dateformat:
    default: Y-m-d
    short: Y-m-d
    long: Y-m-d_H:i
  markdown:
    auto_line_breaks: true
cache:
  enabled: true
  check:
    method: hash
twig:
  cache: true
  debug: false
  auto_reload: false
  autoescape: true
errors:
  display: 0
debugger:
  enabled: false
  censored: true
session:
  secure: true
  httponly: true
  samesite: Strict
